spring:
    cloud:
        nacos:
            discovery:
                server-addr: ${spring.cloud.nacos.server-addr}
                group: springcloud
                namespace: 100513ae-388a-43c2-a181-7fbb37a80a21
            config:
                server-addr: ${spring.cloud.nacos.server-addr}
                file-extension: yaml  # 必须修改成yaml
                group: springcloud
                prefix: ${spring.application.name}
                namespace: 100513ae-388a-43c2-a181-7fbb37a80a21
            server-addr: 127.0.0.1:8848

