spring:
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                group: springcloud
            config:
                server-addr: 127.0.0.1:8848
                file-extension: yaml  # 必须修改成yaml
                group: springcloud
                prefix: ${spring.application.name}
